### ISSUE TITLE
滑动bug

### ISSUE THREAD

**Issue by mycold** [hacknife/CarouselBanner#2]
项目直接运行，布局文件里的app:indicatorSelectedSrc="#222222" app:indicatorUnselectedSrc="#999999"导致指示器不显示，去除此两项指示器显示默认默认颜色

横向banner当手指按住左右划并且不松手的似乎，banner之间的间隔消失，并且会出现前一页覆盖在后一页上的问题

魅蓝matel手机

**Comment by iwdael** [comment]
indicatorSelectedSrc 和indicatorUnselectedSrc 使用的是drawable
